AmbarYonetimi/AmbarYonetimi/ViewModels/BaslikViewModel.cs
using System.Collections.Generic;
using AmbarYonetimi.Models; // BaslikDepo modelin buradaysa ekle

namespace AmbarYonetimi.ViewModels
{
    public class BaslikViewModel
    {
        public List<BaslikDepo> SonHareketler { get; set; }
    }
}

AmbarYonetimi/AmbarYonetimi/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using AmbarYonetimi.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace AmbarYonetimi.Controllers
{
    [Authorize(Roles="admin")]
    public class AdminController : Controller
    {
        private readonly AppDbContext _context;

        public AdminController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var toplamMalzeme = _context.BaslikDepolar.Count() +
                                _context.SungerDepolar.Count() +
                                _context.IskeletDepolar.Count() +
                                _context.KilifDepolar.Count() +
                                _context.KolcakDepolar.Count();

            var toplamGiris = _context.BaslikDepolar.Where(x => x.HareketTipi == "Giriş").Sum(x => x.Miktar)
                               + _context.SungerDepolar.Where(x => x.HareketTipi == "Giriş").Sum(x => x.Miktar);

            var toplamCikis = _context.BaslikDepolar.Where(x => x.HareketTipi == "Çıkış").Sum(x => x.Miktar)
                               + _context.SungerDepolar.Where(x => x.HareketTipi == "Çıkış").Sum(x => x.Miktar);

            var stokDurumu = toplamGiris - toplamCikis;

            var sonIslemler = _context.BaslikDepolar
                .OrderByDescending(x => x.Id)
                .Take(5)
                .Select(x => new {
                    x.Tarih,
                    x.UrunAdi,
                    x.HareketTipi,
                    x.Miktar,
                    x.IslemYapan
                }).ToList();

            ViewBag.ToplamMalzeme = toplamMalzeme;
            ViewBag.ToplamGiris = toplamGiris;
            ViewBag.ToplamCikis = toplamCikis;
            ViewBag.StokDurumu = stokDurumu;
            ViewBag.SonIslemler = sonIslemler;

            return View();
        }
        public IActionResult KullaniciListesi()
        {
            var kullanicilar = _context.Kullanicilar.ToList();
            return View(kullanicilar);
        }

        [HttpGet]
        public IActionResult KullaniciEkle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult KullaniciEkle(Kullanici kullanici)
        {
            _context.Kullanicilar.Add(kullanici);
            _context.SaveChanges();
            return RedirectToAction("KullaniciListesi");
        }

        [HttpGet]
        public IActionResult KullaniciDuzenle(int id)
        {
            var kullanici = _context.Kullanicilar.Find(id);
            return View(kullanici);
        }

        [HttpPost]
        public IActionResult KullaniciDuzenle(Kullanici kullanici)
        {
            _context.Kullanicilar.Update(kullanici);
            _context.SaveChanges();
            return RedirectToAction("KullaniciListesi");
        }

        public IActionResult KullaniciSil(int id)
        {
            var kullanici = _context.Kullanicilar.Find(id);
            _context.Kullanicilar.Remove(kullanici);
            _context.SaveChanges();
            return RedirectToAction("KullaniciListesi");
        }
        public IActionResult Baslik()
        {
            var model = _context.BaslikDepolar.ToList();
            return View(model);
        }

        public IActionResult Sunger()
        {
            var model = _context.SungerDepolar.ToList();
            return View(model);
        }

        public IActionResult Iskelet()
        {
            var model = _context.IskeletDepolar.ToList();
            return View(model);
        }

        public IActionResult Kolcak()
        {
            var model = _context.KolcakDepolar.ToList();
            return View(model);
        }

        public IActionResult Kilif()
        {
            var model = _context.KilifDepolar.ToList();
            return View(model);
        }

        public IActionResult Raporlar()
        {
            // Tablolardan özet bilgiler al
            var toplamBaslik = _context.BaslikDepolar.Sum(x => x.Miktar);
            var toplamSunger = _context.SungerDepolar.Sum(x => x.Miktar);
            var toplamIskelet = _context.IskeletDepolar.Sum(x => x.Miktar);
            var toplamKolcak = _context.KolcakDepolar.Sum(x => x.Miktar);
            var toplamKilif = _context.KilifDepolar.Sum(x => x.Miktar);

            ViewBag.ToplamBaslik = toplamBaslik;
            ViewBag.ToplamSunger = toplamSunger;
            ViewBag.ToplamIskelet = toplamIskelet;
            ViewBag.ToplamKolcak = toplamKolcak;
            ViewBag.ToplamKilif = toplamKilif;

            ViewBag.GenelToplam = toplamBaslik + toplamSunger + toplamIskelet + toplamKolcak + toplamKilif;

            return View();
        }


            [HttpGet]
            public IActionResult GetDepoVerileri(string depo)
            {
                IQueryable<object> data = null;

                switch (depo)
                {
                    case "BaslikDepo":
                        data = _context.BaslikDepolar.Select(x => new { x.Id, x.UrunAdi, x.UrunKodu, x.RafKodu, x.HareketTipi, x.Miktar, x.IslemYapan });
                        break;
                    case "SungerDepo":
                        data = _context.SungerDepolar.Select(x => new { x.Id, x.UrunAdi, x.UrunKodu, x.RafKodu, x.HareketTipi, x.Miktar, x.IslemYapan });
                        break;
                    case "IskeletDepo":
                        data = _context.IskeletDepolar.Select(x => new { x.Id, x.UrunAdi, x.UrunKodu, x.RafKodu, x.HareketTipi, x.Miktar, x.IslemYapan });
                        break;
                    case "KolcakDepo":
                        data = _context.KolcakDepolar.Select(x => new { x.Id, x.UrunAdi, x.UrunKodu, x.RafKodu, x.HareketTipi, x.Miktar, x.IslemYapan });
                        break;
                    case "KilifDepo":
                        data = _context.KilifDepolar.Select(x => new { x.Id, x.UrunAdi, x.UrunKodu, x.RafKodu, x.HareketTipi, x.Miktar, x.IslemYapan });
                        break;
                    default:
                        return Json(new object[] { });
                }

                return Json(data.ToList());
            }

            [HttpGet]
            public IActionResult GetDepoPdf(string depo)
            {
                ViewBag.DepoAdi = depo;
                return View("pdf");
            }


        public IActionResult BaslikSil(int id)
        {
            var entity = _context.BaslikDepolar.Find(id);
            if (entity != null)
            {
                _context.BaslikDepolar.Remove(entity);
                _context.SaveChanges();
            }
            return RedirectToAction("Baslik");
        }

        public IActionResult KolcakSil(int id)
        {
            var entity = _context.KolcakDepolar.Find(id);
            if (entity != null)
            {
                _context.KolcakDepolar.Remove(entity);
                _context.SaveChanges();
            }
            return RedirectToAction("Kolcak");
        }

        public IActionResult SungerSil(int id)
        {
            var entity = _context.SungerDepolar.Find(id);
            if (entity != null)
            {
                _context.SungerDepolar.Remove(entity);
                _context.SaveChanges();
            }
            return RedirectToAction("Sunger");
        }

        public IActionResult IskeletSil(int id)
        {
            var entity = _context.IskeletDepolar.Find(id);
            if (entity != null)
            {
                _context.IskeletDepolar.Remove(entity);
                _context.SaveChanges();
            }
            return RedirectToAction("Iskelet");
        }
        public IActionResult BaslikDuzenle(int id)
        {
            var entity = _context.BaslikDepolar.Find(id);
            if (entity == null)
                return NotFound();

            return View(entity);
        }

        // POST: Formdan gelen veriyi kaydeder
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult BaslikDuzenle(BaslikDepo model)
        {
            if (ModelState.IsValid)
            {
                _context.BaslikDepolar.Update(model);
                _context.SaveChanges();
                return RedirectToAction("Baslik");
            }

            return View(model);
        }

    }
}

AmbarYonetimi/AmbarYonetimi/Controllers/DepoController.cs
using AmbarYonetimi.Models;
using AmbarYonetimi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

public class DepoController : Controller
{
    private readonly AppDbContext _context;

    public DepoController(AppDbContext context)
    {
        _context = context;
    }

    // -------------------- CREATE --------------------
    // GET: Depo/Create
    public IActionResult Create()
    {
        return View(new DepolarViewModel());
    }

    // POST: Depo/Create
    [HttpPost]
    public IActionResult Create(DepolarViewModel model)
    {
        if (!ModelState.IsValid)
        {
            var hatalar = ModelState.Values.SelectMany(v => v.Errors).ToList();
            TempData["Hata"] = string.Join("<br/>", hatalar.Select(h => h.ErrorMessage));
            return View(model);
        }

        int miktarDegeri = (int)(model.HareketTipi == "Çıkış" ? -model.Miktar : model.Miktar);

        switch (model.UrunAdi)
        {
            case "Baslik":
                _context.BaslikDepolar.Add(new BaslikDepo
                {
                    UrunAdi = model.UrunAdi,
                    UrunKodu = model.UrunKodu,
                    RafKodu = model.RafKodu,
                    IslemYapan = model.IslemYapan,
                    HareketTipi = model.HareketTipi,
                    Miktar = miktarDegeri,
                    Tarih = DateTime.Now,
                });
                break;

            case "Iskelet":
                _context.IskeletDepolar.Add(new IskeletDepo
                {
                    UrunAdi = model.UrunAdi,
                    UrunKodu = model.UrunKodu,
                    RafKodu = model.RafKodu,
                    IslemYapan = model.IslemYapan,
                    HareketTipi = model.HareketTipi,
                    Miktar = miktarDegeri,
                    Tarih = DateTime.Now,
                });
                break;

            case "Kilif":
                _context.KilifDepolar.Add(new KilifDepo
                {
                    UrunAdi = model.UrunAdi,
                    UrunKodu = model.UrunKodu,
                    RafKodu = model.RafKodu,
                    IslemYapan = model.IslemYapan,
                    HareketTipi = model.HareketTipi,
                    Miktar = miktarDegeri,
                    Tarih = DateTime.Now,
                });
                break;

            case "Kolcak":
                _context.KolcakDepolar.Add(new KolcakDepo
                {
                    UrunAdi = model.UrunAdi,
                    UrunKodu = model.UrunKodu,
                    RafKodu = model.RafKodu,
                    IslemYapan = model.IslemYapan,
                    HareketTipi = model.HareketTipi,
                    Miktar = miktarDegeri,
                    Tarih = DateTime.Now,
                });
                break;

            case "Sunger":
                _context.SungerDepolar.Add(new SungerDepo
                {
                    UrunAdi = model.UrunAdi,
                    UrunKodu = model.UrunKodu,
                    RafKodu = model.RafKodu,
                    IslemYapan = model.IslemYapan,
                    HareketTipi = model.HareketTipi,
                    Miktar = miktarDegeri,
                    Tarih = DateTime.Now,
                });
                break;
        }

        _context.SaveChanges();
        return RedirectToAction("Index", "Dashboard");
    }

    // -------------------- EDIT --------------------
    // GET: Depo/Edit
    [HttpGet]
    public IActionResult Edit(int id, string tablo)
    {
        object model = null;
        string viewName = "";

        switch (tablo)
        {
            case "Iskelet":
                model = _context.IskeletDepolar.Find(id);
                viewName = "EditIskelet";
                break;
            case "Baslik":
                model = _context.BaslikDepolar.Find(id);
                viewName = "EditBaslik";
                break;
            case "Kilif":
                model = _context.KilifDepolar.Find(id);
                viewName = "EditKilif";
                break;
            case "Kolcak":
                model = _context.KolcakDepolar.Find(id);
                viewName = "EditKolcak";
                break;
            case "Sunger":
                model = _context.SungerDepolar.Find(id);
                viewName = "EditSunger";
                break;
        }

        if (model == null) return NotFound();

        return View(viewName, model);
    }

    // POST: Depo/Edit
    [HttpPost]
    [ActionName("Edit")]
    public async Task<IActionResult> EditPost(int id, string tablo)
    {
        switch (tablo)
        {
            case "Iskelet":
                var iskelet = _context.IskeletDepolar.Find(id);
                if (iskelet == null) return NotFound();
                await TryUpdateModelAsync(iskelet);
                break;

            case "Baslik":
                var baslik = _context.BaslikDepolar.Find(id);
                if (baslik == null) return NotFound();
                await TryUpdateModelAsync(baslik);
                break;

            case "Kilif":
                var kilif = _context.KilifDepolar.Find(id);
                if (kilif == null) return NotFound();
                await TryUpdateModelAsync(kilif);
                break;

            case "Kolcak":
                var kolcak = _context.KolcakDepolar.Find(id);
                if (kolcak == null) return NotFound();
                await TryUpdateModelAsync(kolcak);
                break;

            case "Sunger":
                var sunger = _context.SungerDepolar.Find(id);
                if (sunger == null) return NotFound();
                await TryUpdateModelAsync(sunger);
                break;
        }

        await _context.SaveChangesAsync();
        return RedirectToAction($"{tablo}Depo");
    }

    // -------------------- DELETE --------------------
    [HttpPost]
    public async Task<IActionResult> Delete(int id, string tablo)
    {
        switch (tablo)
        {
            case "Iskelet":
                var iskelet = await _context.IskeletDepolar.FindAsync(id);
                if (iskelet != null) _context.IskeletDepolar.Remove(iskelet);
                break;
            case "Baslik":
                var baslik = await _context.BaslikDepolar.FindAsync(id);
                if (baslik != null) _context.BaslikDepolar.Remove(baslik);
                break;
            case "Kilif":
                var kilif = await _context.KilifDepolar.FindAsync(id);
                if (kilif != null) _context.KilifDepolar.Remove(kilif);
                break;
            case "Kolcak":
                var kolcak = await _context.KolcakDepolar.FindAsync(id);
                if (kolcak != null) _context.KolcakDepolar.Remove(kolcak);
                break;
            case "Sunger":
                var sunger = await _context.SungerDepolar.FindAsync(id);
                if (sunger != null) _context.SungerDepolar.Remove(sunger);
                break;
        }

        await _context.SaveChangesAsync();
        return RedirectToAction($"{tablo}Depo"); // bulunduğun liste sayfasına geri dön
    }

    // -------------------- LİSTELEME --------------------
    public async Task<IActionResult> BaslikDepo()
    {
        return View(await _context.BaslikDepolar.ToListAsync());
    }

    public async Task<IActionResult> KilifDepo()
    {
        return View(await _context.KilifDepolar.ToListAsync());
    }

    public async Task<IActionResult> IskeletDepo()
    {
        return View(await _context.IskeletDepolar.ToListAsync());
    }

    public async Task<IActionResult> KolcakDepo()
    {
        return View(await _context.KolcakDepolar.ToListAsync());
    }

    public async Task<IActionResult> SungerDepo()
    {
        return View(await _context.SungerDepolar.ToListAsync());
    }
}

AmbarYonetimi/AmbarYonetimi/Views/Admin/Baslik.cshtml
@model List<AmbarYonetimi.Models.BaslikDepo>
@{
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Başlık Deposu";
}

<h2>Başlık Deposu</h2>
<a class="btn btn-primary mb-3" href="@Url.Action("Create", "Depo")">+ Yeni Malzeme Ekle</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün Adı</th>
            <th>Ürün Kodu</th>
            <th>Raf Kodu</th>
            <th>Hareket Tipi</th>
            <th>Miktar</th>
            <th>İşlem Yapan</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.UrunAdi</td>
                <td>@item.UrunKodu</td>
                <td>@item.RafKodu</td>
                <td>@item.HareketTipi</td>
                <td>@item.Miktar</td>
                <td>@item.IslemYapan</td>
                <td>
                    <a class="btn btn-sm btn-warning"
                       href="@Url.Action("Edit", "Depo", new { id = item.Id, tablo = "Baslik" })">
                        Düzenle
                    </a>
                    <a class="btn btn-sm btn-danger"
                       href="@Url.Action("BaslikSil", "Admin", new { id = item.Id })"
                       onclick="return confirm('Silmek istediğinize emin misiniz?');">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AmbarYonetimi/AmbarYonetimi/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin Dashboard";
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
}

<h2 class="mb-4">Admin Dashboard</h2>

<div class="row">
    <div class="col-md-3">
        <div class="card text-white bg-primary mb-3">
            <div class="card-body">
                <h5 class="card-title">Toplam Malzeme</h5>
                <p class="card-text fs-4">@ViewBag.ToplamMalzeme</p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-white bg-success mb-3">
            <div class="card-body">
                <h5 class="card-title">Toplam Giriş</h5>
                <p class="card-text fs-4">@ViewBag.ToplamGiris</p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-white bg-danger mb-3">
            <div class="card-body">
                <h5 class="card-title">Toplam Çıkış</h5>
                <p class="card-text fs-4">@ViewBag.ToplamCikis</p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-dark bg-warning mb-3">
            <div class="card-body">
                <h5 class="card-title">Stok Durumu</h5>
                <p class="card-text fs-4">@ViewBag.StokDurumu</p>
            </div>
        </div>
    </div>
</div>

<h4 class="mt-5">Son Yapılan İşlemler</h4>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Tarih</th>
            <th>Ürün</th>
            <th>Hareket Tipi</th>
            <th>Miktar</th>
            <th>İşlem Yapan</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var hareket in ViewBag.SonIslemler)
        {
            <tr>
                <td>@hareket.Tarih</td>
                <td>@hareket.UrunAdi</td>
                <td>@hareket.HareketTipi</td>
                <td>@hareket.Miktar</td>
                <td>@hareket.IslemYapan</td>
            </tr>
        }
    </tbody>
</table>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>

<script>
    async function downloadExcel(depoAdi) {
        try {
            const response = await fetch(`/AdminRapor/GetDepoVerileri?depo=${depoAdi}`);
            const data = await response.json();

            if (!data || data.length === 0) {
                alert("Seçilen depoya ait veri bulunamadı.");
                return;
            }

            const worksheet = XLSX.utils.json_to_sheet(data);
            const workbook = XLSX.utils.book_new();
            XLSX.utils.book_append_sheet(workbook, worksheet, depoAdi);

            XLSX.writeFile(workbook, `${depoAdi}_Rapor.xlsx`);
        } catch (error) {
            console.error("Excel oluşturulurken hata:", error);
            alert("Rapor alınırken hata oluştu.");
        }
    }
</script>

AmbarYonetimi/AmbarYonetimi/Views/Admin/Iskelet.cshtml
@model List<AmbarYonetimi.Models.IskeletDepo>
@{
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
    ViewData["Title"] = "İskelet Deposu";
}

<h2>İskelet Deposu</h2>
<a class="btn btn-primary mb-3" href="@Url.Action("Create", "Depo")">+ Yeni Malzeme Ekle</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün Adı</th>
            <th>Ürün Kodu</th>
            <th>Raf Kodu</th>
            <th>Hareket Tipi</th>
            <th>Miktar</th>
            <th>İşlem Yapan</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.UrunAdi</td>
                <td>@item.UrunKodu</td>
                <td>@item.RafKodu</td>
                <td>@item.HareketTipi</td>
                <td>@item.Miktar</td>
                <td>@item.IslemYapan</td>
                <td>
                    <a class="btn btn-sm btn-warning"
                       href="@Url.Action("Edit", "Depo", new { id = item.Id, tablo = "Iskelet" })">
                        Düzenle
                    </a>
                    <a class="btn btn-sm btn-danger"
                       href="@Url.Action("IskeletSil", "Admin", new { id = item.Id })"
                       onclick="return confirm('Silmek istediğinize emin misiniz?');">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AmbarYonetimi/AmbarYonetimi/Views/Admin/Kilif.cshtml
@model List<AmbarYonetimi.Models.KilifDepo>
@{
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Kılıf Deposu";
}

<h2>Kılıf Deposu</h2>
<a class="btn btn-primary mb-3" href="@Url.Action("Create", "Depo")">+ Yeni Malzeme Ekle</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün Adı</th>
            <th>Ürün Kodu</th>
            <th>Raf Kodu</th>
            <th>Hareket Tipi</th>
            <th>Miktar</th>
            <th>İşlem Yapan</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.UrunAdi</td>
                <td>@item.UrunKodu</td>
                <td>@item.RafKodu</td>
                <td>@item.HareketTipi</td>
                <td>@item.Miktar</td>
                <td>@item.IslemYapan</td>
                <td>
                    <a class="btn btn-sm btn-warning"
                       href="@Url.Action("Edit", "Depo", new { id = item.Id, tablo = "Kilif" })">
                        Düzenle
                    </a>
                    <a class="btn btn-sm btn-danger"
                       href="@Url.Action("Sil", "Kilif", new { id = item.Id })"
                       onclick="return confirm('Silmek istediğinize emin misiniz?');">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AmbarYonetimi/AmbarYonetimi/Views/Admin/Kolcak.cshtml
@model List<AmbarYonetimi.Models.KolcakDepo>
@{
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Kolçak Deposu";
}

<h2>Kolçak Deposu</h2>
<a class="btn btn-primary mb-3" href="@Url.Action("Create", "Depo")">+ Yeni Malzeme Ekle</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün Adı</th>
            <th>Ürün Kodu</th>
            <th>Raf Kodu</th>
            <th>Hareket Tipi</th>
            <th>Miktar</th>
            <th>İşlem Yapan</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.UrunAdi</td>
                <td>@item.UrunKodu</td>
                <td>@item.RafKodu</td>
                <td>@item.HareketTipi</td>
                <td>@item.Miktar</td>
                <td>@item.IslemYapan</td>
                <td>
                    <a class="btn btn-sm btn-warning"
                       href="@Url.Action("Edit", "Depo", new { id = item.Id, tablo = "Kolcak" })">
                        Düzenle
                    </a>
                    <a class="btn btn-sm btn-danger"
                       href="@Url.Action("KolcakSil", "Admin", new { id = item.Id })"
                       onclick="return confirm('Silmek istediğinize emin misiniz?');">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AmbarYonetimi/AmbarYonetimi/Views/Admin/KullaniciListesi.cshtml
@model List<AmbarYonetimi.Models.Kullanici>
@{
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
}

<h2>Kullanıcı Yönetimi</h2>

<a class="btn btn-primary mb-3" href="@Url.Action("KullaniciEkle", "Admin")">+ Yeni Kullanıcı Ekle</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Kullanıcı Adı</th>
            <th>Rol</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.KullaniciAdi</td>
                <td>@item.Rol</td>
                <td>
                    <a class="btn btn-sm btn-warning" href="@Url.Action("KullaniciDuzenle", "Admin", new { id = item.Id })">Düzenle</a>
                    <a class="btn btn-sm btn-danger" href="@Url.Action("KullaniciSil", "Admin", new { id = item.Id })" onclick="return confirm('Silmek istediğine emin misin?');">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AmbarYonetimi/AmbarYonetimi/Views/Admin/Sunger.cshtml
@model List<AmbarYonetimi.Models.SungerDepo>
@{
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Sünger Deposu";
}

<h2>Sünger Deposu</h2>
<a class="btn btn-primary mb-3" href="@Url.Action("Create", "Depo")">+ Yeni Malzeme Ekle</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün Adı</th>
            <th>Ürün Kodu</th>
            <th>Raf Kodu</th>
            <th>Hareket Tipi</th>
            <th>Miktar</th>
            <th>İşlem Yapan</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.UrunAdi</td>
                <td>@item.UrunKodu</td>
                <td>@item.RafKodu</td>
                <td>@item.HareketTipi</td>
                <td>@item.Miktar</td>
                <td>@item.IslemYapan</td>
                <td>
                    <a class="btn btn-sm btn-warning"
                       href="@Url.Action("Edit", "Depo", new { id = item.Id, tablo = "Sunger" })">
                        Düzenle
                    </a>
                    <a class="btn btn-sm btn-danger"
                       href="@Url.Action("SungerSil", "Admin", new { id = item.Id })"
                       onclick="return confirm('Silmek istediğinize emin misiniz?');">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>